PRAGMA defer_foreign_keys = TRUE;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  userID INTEGER PRIMARY KEY,
  narID INTEGER,
  traID INTEGER,
  firstName TEXT COLLATE NOCASE,
  lastName TEXT COLLATE NOCASE,
  email TEXT COLLATE NOCASE UNIQUE NOT NULL,
  avatarURL TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS sessions;

CREATE TABLE IF NOT EXISTS sessions (
  sessionID TEXT PRIMARY KEY NOT NULL,
  userID INTEGER NOT NULL,
  FOREIGN KEY (userID) REFERENCES users(userID),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);