'use client';

import { Raleway } from 'next/font/google';

import './globals.css';
import './Login';

const railway = Raleway({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${railway.className} antialiased`}>{children}</body>
    </html>
  );
}
