export default [
  '220 Swift',
  '3 Bandits',
  'AGM-57X Heatseeker',
  'Alpha',
  'Alpha III',
  'Altimeter',
  'Apollo Little Joe II',
  'Apollo 11 Saturn V',
  'Argent',
  'Ascender',
  'Asteroid Hunter',
  'Astron Skydart II',
  'Astron Sprint XL',
  'Athena',
  'Atomic Aqua',
  'Baby Bertha',
  'Bandito',
  'Banshee',
  'Big Bertha',
  'Big Daddy',
  'Black Diamond',
  'Black Hole',
  'Black Star Voyager',
  'Blast-off Blue',
  'Blenders',
  'Booster-55',
  'Booster-60',
  'Bull Pup 12D',
  'Centuri',
  'Chiller',
  'Chuter-Two',
  'Cobra',
  'Code Red',
  'Comanche-3',
  'Conquest',
  'Cosmic Interceptor',
  'Crossbow SST',
  'Crossfire ISX',
  'Curvilinear',
  'Dark Silver',
  'Dark Zero',
  'Dazzler',
  'Der Red Max',
  'Designer Special',
  'Dragonite',
  'Drifter',
  'Eggscaliber',
  'EPM-010',
  'Estes Jetliner',
  'Estes SLV',
  'Estes Shuttle',
  'Extreme 12',
  'Fat Jax',
  'Firehawk',
  'Firebolt',
  'Firestreak SST',
  'Firestorm',
  'Fletcher',
  'Flip Flyer',
  'Flutter-By',
  'Flying Colors',
  'Fractured',
  'Freefall',
  'Galaxy Gold',
  'Generic E2X',
  'Goblin',
  'Helios',
  'Hi-Flier',
  'Hi-Flier XL',
  'Honest John',
  'Hornet',
  'Humdinger',
  'Hyper Bat',
  'Hyper Dart',
  'Indicator',
  'Journey',
  'L.G.M. 0095',
  'LoadStar II',
  'Lynx',
  'Magician',
  'Majestic',
  'Mammoth',
  'Mega Der Red Max',
  'Mercury Redstone',
  'Metalizer',
  'Meteorite White',
  'Mini Blaster Air',
  'Mini Comanche-3',
  'Mini Fat Boy',
  'Mini Honest John',
  'Mini Max',
  'MIRV',
  'Mix-n-Match-50',
  'Mix-n-Match-55',
  'Mix-n-Match-60',
  'Mongoose',
  'Mosquito',
  'Nike Smoke',
  'Nike Smoke',
  'Nitro',
  'No. 2 Estes Sky Writer',
  'Nova',
  'Odyssey',
  'Orange Crush',
  'Outer-space Orange',
  'Partizon',
  'Phantom Blue',
  'Phoenix Bird',
  'Photon Probe',
  'Power Patrol',
  'Prospector',
  'Puma',
  'QCC Explorer',
  'Quinstar',
  'Red Flare',
  'Red Rider',
  'Rogue Voyager',
  'Rookie',
  'Satellite Silver',
  'Savage',
  'Scorpion',
  'Sequoia',
  'Shattered',
  'Shootig Star',
  'Show Stopper',
  'Shuttle Xpress',
  'Sizzler',
  'Sky Cruiser',
  'Sky Duster',
  'Sky Hawker',
  'Sky Shark',
  'Sky Twister',
  'Sky Warrior',
  'Solar Warrior',
  'Solaris',
  'Spectra',
  'Spirit',
  'Star Orbiter',
  'Star Trooper',
  'STM-012',
  'Super Neon',
  'Super Neon XL',
  'Supernova',
  'Taser Twin',
  'Trajector',
  'Tercel Boost Glider',
  'Top Shot',
  'U.S. Army Patriot M-104',
  'UP Aerospace SpaceLoft',
  'V2',
  'Vagabond',
  'Ventris',
  'Viking',
  'Whirlwind',
  'Wild Flyer',
  'Wizard',
  'Xarconian Cruiser',
  'Yankee',
  'Yellow Star',
  'Zinger',
  '40'
];
