export const MOCK_USER_NAMES = [
  'Adrian Meyer',
  'Adrienne Palmer',
  'Alvin Jensen',
  'Arlene Kennedy',
  'Armando Strickland',
  'Arthur Perry',
  'Barbara Bryan',
  'Beatrice Hicks',
  'Brandi Pena',
  'Brendan Harvey',
  'Cesar Brewer',
  'Cheryl Olson',
  'Clarence Sparks',
  'Cody Gutierrez',
  'Constance Maldonado',
  'Darren Reese',
  'Debbie Diaz',
  'Desiree Glover',
  'Domingo Riley',
  'Doyle Fuller',
  'Earl Lambert',
  'Edgar Bridges',
  'Edna Sims',
  'Franklin Ramos',
  'Fred Porter',
  'Genevieve Simpson',
  'Greg Wheeler',
  'Guy Murray',
  'Hannah Graham',
  'Harvey Tucker',
  'Herbert Moran',
  'Irvin Cohen',
  'Irving Campbell',
  'Jack Klein',
  'Jamie Hayes',
  'Jared Arnold',
  'Jasmine Romero',
  'Javier Medina',
  'Jenna Cooper',
  'Jodi Brock',
  'Johanna Owens',
  'Jon Walters',
  'Julie Valdez',
  'June Barnett',
  'Kenny Jimenez',
  'Kent Ross',
  'Krista Perez',
  'Laurie Fowler',
  'Levi Buchanan',
  'Lillian Webb',
  'Lillie Bush',
  'Lucy Johnson',
  'Lydia Little',
  'Lyle Coleman',
  'Lynn Gonzalez',
  'Maggie Becker',
  'Marian Hawkins',
  'Marianne Horton',
  'Mathew Davidson',
  'Maureen Bennett',
  'Melody Holmes',
  'Melvin Curtis',
  'Mildred Banks',
  'Misty Gill',
  'Natasha Gilbert',
  'Nick Hamilton',
  'Nina Barton',
  'Norma Peterson',
  'Otis Mclaughlin',
  'Patricia Maxwell',
  'Patty Curry',
  'Pauline Walsh',
  'Pearl Higgins',
  'Pete Townsend',
  'Rachael Summers',
  'Raul Guerrero',
  'Roberta Lynch',
  'Roderick Silva',
  'Roman Farmer',
  'Ron French',
  'Sam Butler',
  'Shawna Watkins',
  'Shelia Howard',
  'Shirley Baker',
  'Stacey Burton',
  'Tamara Floyd',
  'Tanya Neal',
  'Theodore Washington',
  'Tomas Wood',
  'Tommy Hampton',
  'Tracey Saunders',
  'Tricia Hansen',
  'Virgil Ortiz',
  'Willard Bates',
  'Wilson Garrett',
  'Woodrow Murphy',
  'Yolanda Nunez',
  'Yvonne Wilkins',
];

export const MOCK_ROCKET_NAMES = [
  '220 Swift',
  '3 Bandits',
  'AGM-57X Heatseeker',
  'Alpha III',
  'Altimeter',
  'Apollo 11 Saturn V',
  'Apollo Little Joe II',
  'Argent',
  'Asteroid Hunter',
  'Astron Skydart II',
  'Astron Sprint XL',
  'Atomic Aqua',
  'Baby Bertha',
  'Bandito',
  'Banshee',
  'Big Bertha',
  'Big Daddy',
  'Black Diamond',
  'Black Hole',
  'Black Star Voyager',
  'Blast-off Blue',
  'Blenders',
  'Booster-55',
  'Booster-60',
  'Bull Pup 12D',
  'Centuri',
  'Chiller',
  'Chuter-Two',
  'Cobra',
  'Code Red',
  'Comanche-3',
  'Conquest',
  'Cosmic Interceptor',
  'Crossbow SST',
  'Crossfire ISX',
  'Curvilinear',
  'Dark Silver',
  'Dark Zero',
  'Dazzler',
  'Der Red Max',
  'Designer Special',
  'Dragonite',
  'Drifter',
  'Eggscaliber',
  'EPM-010',
  'Extreme 12',
  'Fat Jax',
  'Fig Plucker',
  'Finky Starts',
  'Firebolt',
  'Firehawk',
  'Firestorm',
  'Firestreak SST',
  'Flip Flyer',
  'Flutter-By',
  'Flying Colors',
  'Fractured',
  'Freefall',
  'Galaxy Gold',
  'Generic E2X',
  'Goblin',
  'Helios',
  'Hi-Flier XL',
  'Hi-Flier',
  'Honest John',
  'Hornet',
  'Humdinger',
  'Hyper Bat',
  'Hyper Dart',
  'Indicator',
  'Jetliner',
  'Journey',
  'L.G.M. 0095',
  'LoadStar II',
  'Lynx',
  'Magician',
  'Majestic',
  'Mammoth',
  'Mega Der Red Max',
  'Mercury Redstone',
  'Metalizer',
  'Meteorite White',
  'Mini Blaster Air',
  'Mini Comanche-3',
  'Mini Fat Boy',
  'Mini Honest John',
  'Mini Max',
  'MIRV',
  'Mix-n-Match-50',
  'Mix-n-Match-55',
  'Mix-n-Match-60',
  'Mongoose',
  'Mosquito',
  'Nike Smoke',
  'Nike Smoke',
  'Nitro',
  'Nova',
  'Odyssey',
  'Orange Crush',
  'Outer-space Orange',
  'Partizon',
  'Phantom Blue',
  'Pheasant Plucker',
  'Phoenix Bird',
  'Photon Probe',
  'Plaster Man',
  'Power Patrol',
  'Prospector',
  'QCC Explorer',
  'Quinstar',
  'Red Flare',
  'Red Rider',
  'Rogue Voyager',
  'Rookie',
  'Satellite Silver',
  'Savage',
  'Scorpion',
  'Sequoia',
  'Shattered',
  'Shining Wit',
  'Show Stopper',
  'Shuttle Xpress',
  'Shuttle',
  'Sizzler',
  'Sky Cruiser',
  'Sky Duster',
  'Sky Hawker',
  'Sky Shark',
  'Sky Twister',
  'Sky Warrior',
  'Sky Writer',
  'SLV',
  'Solar Warrior',
  'Solaris',
  'Spectra',
  'Spirit',
  'Star Orbiter',
  'Star Trooper',
  'STM-012',
  'Super Neon XL',
  'Super Neon',
  'Supernova',
  'Taser Twin',
  'Tercel Boost Glider',
  'Tooting Shtar',
  'Top Shot',
  'Trajector',
  'U.S. Army Patriot M-104',
  'UP Aerospace SpaceLoft',
  'V2',
  'Vagabond',
  'Ventris',
  'Viking',
  'Whirlwind',
  'Wild Flyer',
  'Wizard',
  'Xarconian Cruiser',
  'Yankee',
  'Yellow Star',
  'Zinger',
];

export const MOCK_LAUNCH_NAMES = [
  'Newbie Noodle-rama',
  'Low Power Pick Up!',
  'Middle Power Madness!!',
  'High Power Hysteria!!!',
];
