'use client';

import { Raleway } from 'next/font/google';

import { useCurrentUser } from '@/app/useCurrentUser';
import Head from 'next/head';
import Link from 'next/link';
import Icon from '../../lib/Icon';
import './globals.css';
import './Login';

const railway = Raleway({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { logout } = useCurrentUser();

  return (
    <html lang='en' suppressHydrationWarning>
      <Head>
        <link rel='icon' type='image/png' href='/favicon.png' />
      </Head>

      <body
        className={`${railway.className} flex flex-col  sm:w-full md:w-2/3 lg:w-1/2 sm:mx-0 md:mx-auto`}
      >
        <details className='dropdown'>
          <summary className='btn m-1 px-2 m-0'>
            <Icon name='list' size='1.5em' />
          </summary>

          <ul className='menu dropdown-content bg-base-100 rounded-box z-[1] w-52 p-2 shadow'>
            <Link href='/'>Home</Link>
            <Link href='/rockets'>Your Rockets</Link>
            <Link href='/profile'>Settings</Link>
            <div className='divider'>Tools</div>
            <Link href='/'>NAR / TRA Member Search</Link>
            <Link href='/'>ThrustCurve Motor Search</Link>
            <div className='divider'>🚀</div>
            <button className='btn btn-sm btm-warning' onClick={logout}>
              Logout
            </button>
          </ul>
        </details>

        {children}
      </body>
    </html>
  );
}
