'use client';

import { Raleway } from 'next/font/google';

import Head from 'next/head';
import './globals.css';
import './Login';

const railway = Raleway({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <Head>
        <link rel='icon' type='image/png' href='/favicon.png' />
      </Head>

      <body className={`${railway.className} antialiased`}>{children}</body>
    </html>
  );
}
