nodeLinker: node-modules
enableGlobalCache: false
# nmHoistingLimits: workspaces

packageExtensions:
  # `node-fetch` declares `encoding` as a `peerDependency`.  We don't dep on it
  # directly, but some transitive deps do and they may not declare this
  "node-fetch@2":
    dependencies:
      encoding: ^0.1.12

  # "@ably-labs/react-hooks@*":
  #   dependencies:
  #     react: ^18.2.0
  #     react-dom: ^18.2.0
  # "@endemolshinegroup/cosmiconfig-typescript-loader@*":
  #   dependencies:
  #     typescript: ^4.9.4
  # "@firebase/auth@*":
  #   dependencies:
  #     "@firebase/app-types": ^0.9.0
  #     "@firebase/util": ^0.4.1
  # "@firebase/database@*":
  #   dependencies:
  #     "@firebase/app-types": ^0.9.0
  # "@graphql-tools/graphql-tag-pluck@*":
  #   dependencies:
  #     "@babel/core": ^7.23.9
  # react-hot-toast@*:
  #   dependencies:
  #     csstype: ^3.1.3
  # filestack-js@*:
  #   dependencies:
  #     typescript: ^4.9.4
