// Generated by Wrangler by running `wrangler types`

interface Env {
	CertsKV: KVNamespace;
	NAR_API_KEY: string;
	NAR_API_ORG: string;
	TRA_USERNAME: string;
	TRA_PASSWORD: string;
	FC_API_KEY: string;
	LAUNCH_DO: DurableObjectNamespace /* LaunchDO */;
	CertsDB: D1Database;
}
