name = "club-members"
main = "./src/index.ts"

compatibility_date = "2022-08-31"

[triggers]
crons = ["0 1 * * *"]

[[kv_namespaces]]
binding = "HPRCerts"
preview_id = "802b03c9c5f24de5977dfe99d54d776a"
id = "40038779c20c43c1bb8ef94e257ca5a5"

[dev]
port = 6543
