name = "club-members"
main = "src/index.ts"

compatibility_date = "2023-05-29"

[triggers]
# Frequency here determines how often NAR logic can fetch a page of results.
# crons = ["0 1 * * *"] # daily @ 1am
crons = ["*/10 * * * *"] # every 10 minutes

# Note: Be sure to update bindings in .envrc
[[d1_databases]]
binding = "CertsDB"
database_name = "certs2"
database_id = "518eaac7-27b4-49e2-8137-6d7ed749abd0"

# Note: Be sure to update bindings in .envrc
[[kv_namespaces]]
binding = "CertsKV"
id = "afad0f09ca4e41e79ce14272da78ad04"
preview_id = "202f9cc828c149d0acfc1238195eeeff"

[[durable_objects.bindings]]
name = "LAUNCH_DO"
class_name = "LaunchDO"

# Durable object migrations (not sure what this is, but wrangler says I need it)
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["LaunchDO"]

[dev]
port = 6543

[observability]
enabled = true
head_sampling_rate = 1
