name = "club-members"
main = "./src/index.ts"

compatibility_date = "2022-08-31"

[triggers]
crons = ["0 1 * * *"]

[[kv_namespaces]]
binding = "ClubMembers"
preview_id = "0507a4b796e64b529694356aefc61228"
id = "4b5d516e066a4fbfbd05423985b1b87c"

[dev]
port = 6543
