name = "club-members"
main = "src/index.ts"

compatibility_date = "2023-05-29"

[triggers]
crons = ["0 1 * * *"]

[[d1_databases]]
binding = "Certs"
database_name = "certs"
database_id = "06f88949-46bc-4e6e-aa3b-c817fc75efb2"

[dev]
port = 6543
