name = "club-members"
main = "src/index.ts"

compatibility_date = "2023-05-29"

[triggers]
# Frequency here determines how often nar_certs script can fetch a page of results.
# crons = ["0 1 * * *"] # daily @ 1am
crons = ["*/10 * * * *"] # every 10 minutes

[[d1_databases]]
binding = "CertsDB"
database_name = "certs2"
database_id = "518eaac7-27b4-49e2-8137-6d7ed749abd0"

[[kv_namespaces]]
binding = "CertsKV"
preview_id = "f8f717868ff844ee9baaeab376a8db64"
id = "8efe9d6e4bea4254812ee315232d41ca"

[dev]
port = 6543

[observability]
enabled = true
head_sampling_rate = 1
